### ISSUE TITLE
Technical improvements

### ISSUE THREAD

**Issue by antonmry** [antonmry/leanmanager#20]
**Phase 0**

- [x] Deploy in GCE
- [x] Terraform
- [x] Persistence
- [ ] Add NATS
- [ ] Refactor three big methods: https://goreportcard.com/report/github.com/antonmry/leanmanager
- [ ] Unit testing
- [ ] Fix member.Name vs. member.ID, IDs in general
- [ ] Some stability things (panics, loose connection, etc)
- [ ] if error receiving message, we should reconnect!
- [ ] life test
- [ ] ~~Travis~~ [Concourse](https://concourse.ci)

**Phase 1**

- [ ] Migrate to Go-kit: github and slack webhooks
- [ ] Packer: https://medium.com/@kcearns/packer-and-docker-push-9537b6c0ec89#.my5r0u1s2
- [ ] Godep u other?

**Comment by antonmry** [comment]
Interesting badges: 
- https://goreportcard.com/report/github.com/antonmry/leanmanager
- https://github.com/containous/traefik
- https://github.com/antham/doc-hunt
