### ISSUE TITLE
Improve customer experience in Daily Meetings

### ISSUE THREAD

**Issue by antonmry** [antonmry/leanmanager#3]
- [x] validate daily responses #16 #17 #18 #19 
- [x] show help commands #15
- [x] schedule the daily meeting #10 #11 #12 #13 #14
- [x] resume command #6
- [x] timeouts: https://gobyexample.com/timeouts #6
- [x] how we differ messages by channel and user? channelID shouldn't be a global variable #5
- [x] avoid @leanmanager prefix when possible! #5
